# Generated by Django 4.0.1 on 2022-01-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_alter_diagnosis_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
